# repos:
#   - repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: v0.5.1  # Use the latest stable version
#     hooks:
#       - id: ruff
#         args: [--fix]

#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.5.0  # Latest version
#     hooks:
#       - id: trailing-whitespace
#       - id: end-of-file-fixer
#       - id: check-yaml
#       - id: check-added-large-files
