[tool.ruff]
line-length = 88
select = ["ALL"]
ignore = ["D203", "D213"]
exclude = ["external/"]

[tool.ruff.lint.per-file-ignores]
"docs/source/conf.py" = ["INP001", "D100", "A001"]

[lint.pydocstyle]
convention = "google"