[tool.ruff]
line-length = 88
exclude = ["external/"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D203", "D213", "FIX002"]

[tool.ruff.lint.per-file-ignores]
"docs/source/conf.py" = ["INP001", "D100", "A001"]
"src/dialect/utils/simulate.py" = ["PLR0913"]
"src/dialect/utils/plotting.py" = ["PLR0913", "FBT001"]
"src/dialect/utils/postprocessing.py" = ["FBT001"]
"src/dialect/utils/wesme.py" = ["E402"]
"src/dialect/utils/logger.py" = ["SLF001", "FBT001", "FBT002"]
"src/dialect/utils/generate.py" = ["S603"]
"src/dialect/utils/identify.py" = ["FBT001"]
"src/dialect/utils/argument_parser.py" = ["FBT001", "FBT002", "PLR0913", "C901"]
"src/dialect/utils/compare.py" = ["FBT001"]
"setup.py" = ["D100"]

[lint.pydocstyle]
convention = "google"
