[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D203", "D213"]

[tool.ruff.lint.per-file-ignores]
"docs/source/conf.py" = ["INP001", "D100", "A001"]

[lint.pydocstyle]
convention = "google"