[tool.ruff]
line-length = 88
exclude = ["external/"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D203", "D213"]

[tool.ruff.lint.per-file-ignores]
"docs/source/conf.py" = ["INP001", "D100", "A001"]
"setup.py" = ["D100"]

[lint.pydocstyle]
convention = "google"
