"""Regenerate the ME/CO supplementary table (Table S5) with R1's requested columns.

Per cohort: total pairs, hypermutator-sample fraction, and per-BMR (CBaSE / Dig /
MutSigCV2) ME and CO counts at a SINGLE symmetric FDR -- chi2_1 p-value -> Benjamini-
Hochberg, q < FDR for both directions (direction from sign of rho). Matches the
baselines (DISCOVER/Fisher/WeSME/WeSCO all use FDR<0.01 both), replacing DIALECT's
unjustified asymmetric ME 0.01 / CO 0.10.

Hypermutator fraction = fraction of samples whose analyzed-gene count exceeds 10x the
cohort median -- the burden heterogeneity driving CO saturation under a per-gene BMR.

Usage:  python -m analysis.supp_co_summary --fdr 0.01 --out output/supp_co_summary
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from analysis.bmr_fdr_comparison import call_significant

BMRS = ("cbase", "dig", "mutsig")
BMR_LABEL = {"cbase": "CBaSE", "dig": "Dig", "mutsig": "MutSigCV2"}
SOURCES = [
    ("TCGA", Path("output/pancan")),
    ("MSK-IMPACT", Path("output/msk/IMPACT2026")),
    ("MSK-CHORD", Path("output/msk/CHORD2024")),
]


def hypermutator_fraction(cm: pd.DataFrame, mult: float = 10.0) -> float:
    """Fraction of samples whose total analyzed-gene count exceeds mult x the median."""
    tot = cm.sum(axis=1)
    med = float(tot.median())
    return float((tot > mult * med).mean()) if med > 0 else 0.0


def cohort_row(study: str, cohort: str, cdir: Path, fdr: float) -> dict | None:
    """One Table-S5 row: counts + hypermutator fraction + per-BMR ME/CO at the FDR."""
    cm_fn = cdir / "count_matrix.csv"
    if not cm_fn.exists():
        return None
    cm = pd.read_csv(cm_fn, index_col=0)
    row = {
        "study": study, "cohort": cohort, "N": cm.shape[0],
        "median_tmb": int(cm.sum(axis=1).median()),
        "hyper_frac": round(hypermutator_fraction(cm), 3),
        "total_pairs": None,
    }
    for bmr in BMRS:
        fn = cdir / f"id_{bmr}" / "pairwise_interaction_results.csv"
        if not fn.exists():
            row[f"{bmr}_ME"] = row[f"{bmr}_CO"] = None
            continue
        called = call_significant(pd.read_csv(fn), fdr)
        row["total_pairs"] = len(called)
        sig = called[called["significant"]]
        row[f"{bmr}_ME"] = int((sig["direction"] == "ME").sum())
        row[f"{bmr}_CO"] = int((sig["direction"] == "CO").sum())
    return row


def to_latex(df: pd.DataFrame, fdr: float) -> str:
    """Compact LaTeX longtable of TCGA rows (per-BMR CO counts + hyp. frac.)."""
    sub = df[df["study"] == "TCGA"].sort_values("hyper_frac", ascending=False)
    lines = [
        f"% auto-generated by analysis/supp_co_summary.py -- symmetric FDR<{fdr:.2f}",
        r"\begin{longtable}{lrrrrrr}",
        r"\toprule",
        r"Cohort & $N$ & hyp.\ frac. & pairs & CO$_{\mathrm{CBaSE}}$ "
        r"& CO$_{\mathrm{Dig}}$ & CO$_{\mathrm{MutSig}}$ \\",
        r"\midrule",
    ]

    def _f(x: object) -> str:
        return "--" if pd.isna(x) else str(int(x))

    for _, r in sub.iterrows():
        lines.append(
            f"{r['cohort']} & {int(r['N'])} & {r['hyper_frac']:.2f} & "
            f"{_f(r['total_pairs'])} & {_f(r['cbase_CO'])} & {_f(r['dig_CO'])} "
            f"& {_f(r['mutsig_CO'])} \\\\",
        )
    lines += [r"\bottomrule", r"\end{longtable}"]
    return "\n".join(lines)


def main() -> None:
    """Build the supplementary ME/CO summary across all cohorts and BMRs."""
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--fdr", type=float, default=0.01)
    p.add_argument("--out", default="output/supp_co_summary")
    args = p.parse_args()
    rows = []
    for study, root in SOURCES:
        if not root.exists():
            continue
        for cdir in sorted(root.iterdir()):
            if cdir.is_dir():
                r = cohort_row(study, cdir.name, cdir, args.fdr)
                if r:
                    rows.append(r)
    df = pd.DataFrame(rows)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    df.to_csv(out / "supp_co_summary.csv", index=False)
    (out / "table_s5.tex").write_text(to_latex(df, args.fdr))

    tcga = df[df["study"] == "TCGA"]
    print(f"symmetric FDR<{args.fdr}: {len(df)} cohorts ({len(tcga)} TCGA)")
    print("\nTCGA CO saturation, sorted by hypermutator fraction (CBaSE vs MutSigCV2):")
    show = tcga.sort_values("hyper_frac", ascending=False)[
        ["cohort", "N", "hyper_frac", "total_pairs", "cbase_CO", "dig_CO", "mutsig_CO"]
    ].head(12)
    print(show.to_string(index=False))
    print(f"\nwrote {out}/supp_co_summary.csv + table_s5.tex")


if __name__ == "__main__":
    main()
